<ADSWorkspace Revision="11" Version="100">
    <Workspace Name="">
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_standard_layers" />
        <Library Name="adstechlib" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="Stripline_LPF_lib" />
        <Dataset Name="Stripline.ds" />
        <Dataset Name="Stripline_a.ds" />
        <Dataset Name="Stripline_box.ds" />
        <Dataset Name="Stripline_box_a.ds" />
        <Dataset Name="Stripline_box_mom.ds" />
        <Dataset Name="Stripline_box_mom_a.ds" />
        <Dataset Name="XBALUN_HFSS.ds" />
        <Dataset Name="XBALUN_meas_s11.ds" />
        <Dataset Name="XBALUN_meas_s21.ds" />
        <Log Name="conversion_results.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Preferences Name="Stripline_LPF_lib_lay.prf" />
        <Text Name="out.txt" />
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Layer_Preference Name="Stripline_LPF_lib.layerprf" />
        <Log Name="search_history.log" />
        <Folder Name="01_ReadMe">
            <Cell Name="Stripline_LPF_lib:README" />
        </Folder>
        <Folder Name="02_Stripline_LPF_without_Box">
            <Cell Name="Stripline_LPF_lib:Stripline" />
            <Data_Display Name="stripline.dds" />
            <Substrate Name="Stripline_LPF_lib:dsn_Stripline.subst" />
        </Folder>
        <Folder Name="03_Stripline_LPF_with_Box">
            <Data_Display Name="stripline_v1.dds" />
            <Cell Name="Stripline_LPF_lib:Stripline_box" />
            <Substrate Name="Stripline_LPF_lib:dsn_Stripline_box.subst" />
        </Folder>
        <ConfigFile Name="dds.cfg" />
    </Workspace>
</ADSWorkspace>
