<ADSWorkspace Revision="11" Version="100">
    <Workspace Name="">
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_standard_layers" />
        <Library Name="adstechlib" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="EVM_Examples_lib" />
        <Dataset Name="EVM_NonLinearAmp_Ref.ds" />
        <Dataset Name="EVM_SAWFilter_1Pin_Ref.ds" />
        <Dataset Name="EVM_SAWFilter_2Pin_Ref.ds" />
        <Dataset Name="SAWFilter_Character_Ref.ds" />
        <Log Name="conversion_results.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Folder Name="01_ReadMe">
            <Cell Name="EVM_Examples_lib:Readme" />
        </Folder>
        <Folder Name="02_EVM">
            <Cell Name="EVM_Examples_lib:EVM_NonLinearAmp" />
            <Cell Name="EVM_Examples_lib:EVM_SAWFilter_1Pin" />
            <Cell Name="EVM_Examples_lib:EVM_SAWFilter_2Pin" />
            <Data_Display Name="EVMResults.dds" />
        </Folder>
        <Folder Name="03_SAW_Filter">
            <Cell Name="EVM_Examples_lib:SAWFilter_Character" />
            <Data_Display Name="SAWFilter_Character.dds" />
        </Folder>
        <Log Name="search_history.log" />
    </Workspace>
</ADSWorkspace>
