<ADSWorkspace Revision="36" Version="100">
    <Workspace Name="">
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="COSIM_LAB_PRJ_lib" />
        <Dataset Name="COSIM_QPSK.ds" />
        <Dataset Name="COSIM_QPSK_constl_correct.ds" />
        <Dataset Name="COSIM_QPSK_out.ds" />
        <Dataset Name="FULL_COSIM_16QAM.ds" />
        <Dataset Name="FULL_COSIM_16QAM_constel.ds" />
        <Dataset Name="FULL_COSIM_16QAM_constelTEST.ds" />
        <Dataset Name="FULL_COSIM_16QAM_Interactive.ds" />
        <Dataset Name="FULL_SOC1.ds" />
        <Dataset Name="FULL_SOC_constel.ds" />
        <Dataset Name="full_system1.ds" />
        <Dataset Name="full_system2.ds" />
        <Dataset Name="Gilcell_pa_sweep2.ds" />
        <Dataset Name="IQ_DEMOD_Subsystem.ds" />
        <Dataset Name="IQ_MOD_CKT.ds" />
        <Dataset Name="IQ_Mod_subsystem.ds" />
        <Dataset Name="IQ_Mod_subsystem_out.ds" />
        <Dataset Name="IQ_Mod_system.ds" />
        <Dataset Name="IQ_Mod_system_out.ds" />
        <Dataset Name="Mixer_Freq_resp_7dbmlo.ds" />
        <Dataset Name="Mixer_Freq_sweep.ds" />
        <Dataset Name="Mixer_Freq_sweep_7dbm-lo.ds" />
        <Dataset Name="Mixer_Freq_sweep_7dbmlo.ds" />
        <Dataset Name="Mixer_Freq_sweep_out.ds" />
        <Dataset Name="Mixer_GilCel.ds" />
        <Dataset Name="Mixer_GilCel_DC.ds" />
        <Dataset Name="mixer_opt_convgain.ds" />
        <Dataset Name="Mixer_Power_sweep.ds" />
        <Dataset Name="Mixer_Power_sweep_out.ds" />
        <Dataset Name="Mixer_Power_swep_out2.ds" />
        <Dataset Name="Mixr_Pa_sweep.ds" />
        <Dataset Name="Mixr_Pa_sweep_Kry.ds" />
        <Dataset Name="Mixr_Pa_sweep_Kry_out.ds" />
        <Dataset Name="Mixr_Pa_sweep_out.ds" />
        <Dataset Name="Mixr_Pa_sweepOSeq2.ds" />
        <Dataset Name="modulator_test.ds" />
        <Dataset Name="PA_2stg.ds" />
        <Dataset Name="PA_2stg_1dBcomp.ds" />
        <Dataset Name="PA_2stg_1dBcomp_out.ds" />
        <Dataset Name="PA_2stg_opt_gain.ds" />
        <Dataset Name="phase_shift.ds" />
        <Dataset Name="phase_shift_out.ds" />
        <Dataset Name="RC_Filter_Impulse.ds" />
        <Dataset Name="Wilkinson.ds" />
        <Dataset Name="Wilkinson_out.ds" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="dfilter.cfg" />
        <ConfigFile Name="hpeesofbrowser.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Log Name="search_history.log" />
        <Folder Name="01_ReadMe">
            <Cell Name="COSIM_LAB_PRJ_lib:ReadMe" />
        </Folder>
        <Folder Name="02_FULL_COSIM_16QAM_Interactive_Constel">
            <Cell Name="COSIM_LAB_PRJ_lib:FULL_COSIM_16QAM_constel" />
            <Cell Name="COSIM_LAB_PRJ_lib:FULL_COSIM_16QAM_Interactive" />
        </Folder>
        <Folder Name="03_FULL_SOC1_Constel">
            <Cell Name="COSIM_LAB_PRJ_lib:FULL_SOC1" />
            <Cell Name="COSIM_LAB_PRJ_lib:FULL_SOC_constel" />
        </Folder>
        <Folder Name="04_IQ_Mod_Demod_systems">
            <Cell Name="COSIM_LAB_PRJ_lib:IQ_DEMOD_Subsystem" />
            <Cell Name="COSIM_LAB_PRJ_lib:IQ_Mod_subsystem" />
            <Cell Name="COSIM_LAB_PRJ_lib:IQ_MOD_CKT" />
            <Cell Name="COSIM_LAB_PRJ_lib:IQ_Mod_system" />
            <Data_Display Name="IQ_Mod_systm.dds" />
            <Data_Display Name="IQ_Mod_subsystm.dds" />
            <Data_Display Name="modulator_test_out.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:modulator_test" />
        </Folder>
        <Folder Name="05_Mixer_Designs">
            <Cell Name="COSIM_LAB_PRJ_lib:Mixer_Freq_sweep" />
            <Data_Display Name="Mixer_Freq_swep.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:Mixer_GilCel" />
            <Cell Name="COSIM_LAB_PRJ_lib:Mixer_Power_sweep" />
            <Data_Display Name="Mixer_Power_swep1.dds" />
            <Data_Display Name="Mixer_Power_swep2.dds" />
            <Data_Display Name="mixer_swept_results.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:Mixr_Pa_sweep" />
            <Cell Name="COSIM_LAB_PRJ_lib:Mixr_Pa_sweep_Kry" />
            <Data_Display Name="Mixr_Pa_swep.dds" />
            <Data_Display Name="Mixr_Pa_swep_Kry.dds" />
        </Folder>
        <Folder Name="06_Filters_Dividers_Oscillators">
            <Cell Name="COSIM_LAB_PRJ_lib:BPF2G_WB" />
            <Cell Name="COSIM_LAB_PRJ_lib:Wilkinson" />
            <Data_Display Name="wilkinsn.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:test_osc" />
            <Cell Name="COSIM_LAB_PRJ_lib:Synth_RCfiltA" />
            <Cell Name="COSIM_LAB_PRJ_lib:Synth_16QAM_IQ" />
            <Data_Display Name="RC_Filter_Impulse.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:RC_Filter_Impulse" />
            <Cell Name="COSIM_LAB_PRJ_lib:rc1" />
            <Data_Display Name="phase_shift.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:phase_shift" />
        </Folder>
        <Folder Name="07_PA_QPSK_QAM_Designs">
            <Cell Name="COSIM_LAB_PRJ_lib:PA_2stg_opt_gain" />
            <Cell Name="COSIM_LAB_PRJ_lib:PA_2stg_1dBcomp" />
            <Data_Display Name="PA_2stg_1dBcom.dds" />
            <Data_Display Name="PA_2stg.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:PA_2stg" />
            <Data_Display Name="FULL_SOC1_out.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:FULL_COSIM_16QAM" />
            <Data_Display Name="FULL_COSIM_16Q.dds" />
            <Cell Name="COSIM_LAB_PRJ_lib:COSIM_QPSK_constl_correct" />
            <Cell Name="COSIM_LAB_PRJ_lib:COSIM_QPSK" />
        </Folder>
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_verification_test_bench" />
        <Library Name="ads_pelib" />
        <Library Name="ads_builtin" />
        <Data_Display Name="FULL_COSIM_16QAM_Interactive.dds" />
        <Data_Display Name="FULL_SOC_constel.dds" />
        <Dataset Name="FULL_SOC1Test.ds" />
        <Log Name="netlist.log" />
        <Preferences Name="COSIM_LAB_PRJ_lib_lay.prf" />
        <ConfigFile Name="dds.cfg" />
        <Data_Display Name="COSIM_QPSK.dds" />
        <Data_Display Name="COSIM_QPSK_constl_correct.dds" />
    </Workspace>
</ADSWorkspace>
