<ADSWorkspace Revision="7" Version="100">
    <Workspace Name="">
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_standard_layers" />
        <Library Name="adstechlib" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="WMAN_WiBro_lib" />
        <Dataset Name="Ref_WiBro_DL_AWGN_BER_Rate0.ds" />
        <Dataset Name="Ref_WiBro_DL_AWGN_BER_Rate1.ds" />
        <Dataset Name="Ref_WiBro_DL_AWGN_BER_Rate2.ds" />
        <Dataset Name="Ref_WiBro_DL_AWGN_BER_Rate3.ds" />
        <Dataset Name="Ref_WiBro_DL_AWGN_BER_Rate4.ds" />
        <Dataset Name="Ref_WiBro_DL_AWGN_BER_Rate5.ds" />
        <Dataset Name="Ref_WiBro_DL_AWGN_BER_Rate6.ds" />
        <Dataset Name="Ref_WiBro_DL_TxEVM.ds" />
        <Dataset Name="Ref_WiBro_UL_TxEVM.ds" />
        <Log Name="conversion_results.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="mil_layout.prf" />
        <Preferences Name="mil_schematic.prf" />
        <Preferences Name="schematic.prf" />
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Log Name="search_history.log" />
        <Folder Name="01_ReadMe">
            <Cell Name="WMAN_WiBro_lib:ReadMe" />
        </Folder>
        <Folder Name="02_DownLink">
            <Cell Name="WMAN_WiBro_lib:WiBro_DL_AWGN_BER" />
            <Data_Display Name="WiBro_DL_AWGN_BER.dds" />
            <Cell Name="WMAN_WiBro_lib:WiBro_DL_TxEVM" />
            <Data_Display Name="WiBro_DL_TxEVM.dds" />
        </Folder>
        <Folder Name="03_UpLink">
            <Cell Name="WMAN_WiBro_lib:WiBro_UL_TxEVM" />
            <Data_Display Name="WiBro_UL_TxEVM.dds" />
            <Cell Name="WMAN_WiBro_lib:WiBro_UL_VSA" />
        </Folder>
    </Workspace>
</ADSWorkspace>
