<ADSWorkspace Revision="11" Version="100">
    <Workspace Name="">
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_standard_layers" />
        <Library Name="adstechlib" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="OFDM_WLAN_lib" />
        <Log Name="conversion_results.log" />
        <Log Name="netlist.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Folder Name="01_ReadMe">
            <Cell Name="OFDM_WLAN_lib:ReadMe" />
        </Folder>
        <Log Name="search_history.log" />
        <ConfigFile Name="dds.cfg" />
        <Folder Name="02_Column Multiplier">
            <Cell Name="OFDM_WLAN_lib:COLUMN_MULT" />
            <Data_Display Name="Cx_Data_In.dds" />
            <Data_Display Name="Cx_Data_IQ.dds" />
            <Data_Display Name="Guard_Interval.dds" />
            <Cell Name="OFDM_WLAN_lib:M4_MODULE" />
        </Folder>
        <Folder Name="03_OFDM ">
            <Cell Name="OFDM_WLAN_lib:OFDM_MOD" />
            <Data_Display Name="OFDM_Spectra.dds" />
            <Data_Display Name="PeakToAverage.dds" />
            <Cell Name="OFDM_WLAN_lib:REED_MULLER_ENCODER" />
            <Data_Display Name="sig_gen.dds" />
            <Data_Display Name="Spectrum_ACPR.dds" />
        </Folder>
    </Workspace>
</ADSWorkspace>
