<ADSWorkspace Revision="23" Version="100">
    <Workspace Name="">
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="CMMB" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="RFSystem_lib" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_rflib" />
        <Library Name="ads_schematic_layers" />
        <Library Name="ads_simulation" />
        <Library Name="ads_sources" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_tlines" />
        <Library Name="adstechlib" />
        <Library Name="cdma2000" />
        <Library Name="empro_standard_layers" />
        <Dataset Name="ACPR_IS_136.ds" />
        <Dataset Name="Amp_TOI.ds" />
        <Dataset Name="Diplexer_test.ds" />
        <Dataset Name="Linear_Sweep.ds" />
        <Dataset Name="LS_Mix_Sweep.ds" />
        <Dataset Name="Mixer_Noise1.ds" />
        <Dataset Name="Mixer_Noise2.ds" />
        <Dataset Name="Mixer_TOI.ds" />
        <Dataset Name="PCS_Rx_Budget.ds" />
        <Dataset Name="PCS_Rx_TOI_test.ds" />
        <Log Name="conversion_results.log" />
        <Log Name="netlist_WIN_64_XP.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="PCS_receive_Budget_schem.prf" />
        <Preferences Name="schematic.prf" />
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <ConfigFile Name="dds.cfg" />
        <Log Name="netlist.log" />
        <Log Name="search_history.log" />
        <Folder Name="01_ReadMe">
            <Cell Name="RFSystem_lib:ReadMe" />
        </Folder>
        <Folder Name="02_Amplifier">
            <Cell Name="RFSystem_lib:ACPR_IS_136" />
            <Data_Display Name="ACPR_IS_136received.dds" />
            <Data_Display Name="ACPR_IS_136transmitted.dds" />
            <Cell Name="RFSystem_lib:Amp_TOI" />
            <Data_Display Name="Amp_TOI.dds" />
            <Data_Display Name="IS_136_ConstEVM.dds" />
        </Folder>
        <Folder Name="03_Diplexer">
            <Cell Name="RFSystem_lib:Diplexer_test" />
            <Data_Display Name="Diplexer_test.dds" />
            <Cell Name="RFSystem_lib:PCS_diplexer" />
        </Folder>
        <Folder Name="04_Mixer">
            <Cell Name="RFSystem_lib:LS_Mix_Sweep" />
            <Data_Display Name="LS_Mix_Sweep.dds" />
            <Cell Name="RFSystem_lib:Mixer_Noise1" />
            <Data_Display Name="Mixer_Noise1.dds" />
            <Cell Name="RFSystem_lib:Mixer_Noise2" />
            <Data_Display Name="Mixer_Noise2.dds" />
            <Cell Name="RFSystem_lib:Mixer_TOI" />
            <Data_Display Name="Mixer_TOI.dds" />
        </Folder>
        <Folder Name="05_PCS">
            <Cell Name="RFSystem_lib:Linear_Budget" />
            <Cell Name="RFSystem_lib:Linear_Sweep" />
            <Data_Display Name="Linear_Sweep.dds" />
            <Cell Name="RFSystem_lib:PCS_RF_rcvr" />
            <Cell Name="RFSystem_lib:PCS_RX" />
            <Data_Display Name="PCS_Rx_Bud_Gain.dds" />
            <Data_Display Name="PCS_Rx_Bud_Power.dds" />
            <Cell Name="RFSystem_lib:PCS_Rx_Budget" />
            <Cell Name="RFSystem_lib:PCS_Rx_TOI_test" />
            <Data_Display Name="PCS_Rx_TOI_test.dds" />
            <Cell Name="RFSystem_lib:PCS_Tx" />
        </Folder>
    </Workspace>
</ADSWorkspace>
